### Listing 3-1 Simple Mathematics Operations

In [1]:
# Math with Constant Tensors

In [3]:
import tensorflow as tf

In [4]:
const_a = tf.constant(3.6)

In [5]:
const_b = tf.constant(1.2)

In [6]:
total = const_a + const_b

In [7]:
quot = tf.div(const_a, const_b)

In [8]:
# Math with Random Tensors

In [9]:
rand_a = tf.random_normal([3], 2.0)

In [10]:
rand_b = tf.random_normal([3], 1.0, 4.0)

In [11]:
diff = tf.subtract(rand_a, rand_b)

In [12]:
# Vector Multiplication

In [13]:
vec_a = tf.linspace(0.0, 3.0, 4)

In [14]:
vec_b = tf.fill([4, 1], 2.0)

In [15]:
prod = tf.multiply(vec_a, vec_b)

In [16]:
dot = tf.tensordot(vec_a, vec_b, 1)

In [17]:
# Matrix Multiplication

In [18]:
mat_a = tf.constant([[2, 3], [1, 2], [4, 5]])
mat_b = tf.constant([[6, 4, 4], [3, 7, 2]])

In [19]:
mat_prod = tf.matmul(mat_a, mat_b)

In [20]:
# Execute the Operations

In [21]:
with tf.Session() as sess:
    print("Sum: %f" % sess.run(total))
    print("Quotient: %f" % sess.run(quot))
    print("Difference: ", sess.run(diff))
    print("Element-wise product: ", sess.run(prod))
    print("Dot product: ", sess.run(dot))
    print("Matrix product: ", sess.run(mat_prod))

Sum: 4.800000
Quotient: 3.000000
Difference:  [-0.05368757 -5.37077045  7.37934637]
Element-wise product:  [[ 0.  2.  4.  6.]
 [ 0.  2.  4.  6.]
 [ 0.  2.  4.  6.]
 [ 0.  2.  4.  6.]]
Dot product:  [ 12.]
Matrix product:  [[21 29 14]
 [12 18  8]
 [39 51 26]]


In [22]:
3.6/1.2

3.0

The application creates and operates on constant tensors, random tensors, vectors and matrices. To process vectors, the application performs element-wise multiplication with tf.multiply. Then, it computes the dot product of the two vectors with tf.tensordot.

The last portion of code deserves explanation. The application creates a Session named sess and calls its run method once for each operation to be performed. To understand what sessions are and how they work, you need to be familiar with graphs. 